const wordReplacementsMap = {
  guys: [
    'associates',
    'band',
    'brood',
    'chums',
    'cohort',
    'colleagues',
    'companions',
    'compatriots',
    'confidants',
    'consorts',
    'coterie',
    'coven',
    'crew',
    'crowd',
    'everybody',
    'folks',
    'friends',
    'gang',
    'horde',
    'humans',
    'mates',
    'mortals',
    'pack',
    'pals',
    'peers',
    'people',
    'posse',
    'squad',
    'syndicate',
    'team',
    'teammates',
    'throng',
    'troop',
    "y'all",
  ],
  whitelist: [ 'allow list', 'safe list', 'permit list', 'include list', 'prefer list' ],
  blacklist: [ 'deny list', 'unsafe list', 'block list', 'exclude list', 'avoid list' ],
  master: [ 'main', 'primary', 'leader', 'source' ],
  slave: [ 'secondary', 'subordinate', 'replica' ],
  transgendered: [ 'transgender' ],
};

export default wordReplacementsMap;
